
Read the FCSs
```{r}
library(dplyr)
library(tidyr)
library(reshape2)
library(readxl)

library(flowCore)
library(CATALYST)
library(FlowSOM)

library(ggplot2)
library(ggpubr)

library(ComplexHeatmap)
library(cowplot)

#BiocManager::install("diffcyt")
library(diffcyt)
```
#Load FCS and metadata files
```{r}
prefix <- "CyTOF.analysis"
printGraph <- F
fixed_seed <- 1234

source("CATALYST.function.R")
```

```{r}
SCE_RDS <- "SCE.clustSOM100.k20.byAllMarkers.tSNE.UMAP.merged.rds"
sce_all <- readRDS(file=paste(prefix,SCE_RDS,sep="."))
```

#Generate a data frame of the abundancers of each cell type
```{r}
sce_all_day1 <- filterSCE(sce_all, k="merging1", timepoint == "Day1", !(cluster_id %in% c("others","no markers")))
sce_all_day1_abundances <- getAbundanceStats(sce_all_day1, k = "merging1", group_by = "Tx_Group")
sce_all_day1_abundances$timepoint <- "Day1"
                      
sce_all_day29 <- filterSCE(sce_all, k = "merging1", timepoint == "Day29", !(cluster_id %in% c("others","no markers")))
sce_all_day29_abundances <- getAbundanceStats(sce_all_day29, k = "merging1", group_by = "Tx_Group")
sce_all_day29_abundances$timepoint <- "Day29"

sce_all_day0 <- filterSCE(sce_all, k = "merging1", timepoint == "Day0", !(cluster_id %in% c("others","no markers")))
sce_all_day0_abundances <- getAbundanceStats(sce_all_day0, k = "merging1", group_by = "Tx_Group")
sce_all_day0_abundances$timepoint <- "Day0"
sce_all_day0_abundances$Tx_Group <- "PreTx"

combined_abundances <- as.data.frame(rbind(sce_all_day1_abundances,sce_all_day29_abundances,sce_all_day0_abundances))
#write.csv(combined_abundances,file=paste(prefix,"CellTypeAbundances.csv",sep="."))

sce_all_day1_29 <- filterSCE(sce_all, k="merging1", timepoint %in% c("Day1","Day29"), !(cluster_id %in% c("others","no markers")))
sce_all_day1_29_abundances <- getAbundanceStats(sce_all_day1_29, k = "merging1", group_by = "Tx_Group")
#sce_all_day1_29_abundances <-   as.data.frame(rbind(sce_all_day1_abundances,sce_all_day29_abundances))                   

```


```{r}
Tx_color_palette <- c("#5C899B","#9B5C89","#899B5C")
comparisonList <- list(c("Placebo","PolyICLC"),c("Placebo","Resiquimod"))

plotAbundancesWithStats_ggarrange(sce_all_day1_abundances, 
                                       by="cluster_id", 
                                       group_by = "Tx_Group", 
                                       outfile=paste(prefix,"Abundances.Day1.pdf",sep="."),
                                       group_by_palette = Tx_color_palette,
                                       #group_by_stats_ref_group = "Placebo", 
                                       group_by_stats_comparisons = comparisonList,
                                       group_by_stats_method = "wilcox.test",
                                       nrows=2,width_single=80,height_single=120)

plotAbundancesWithStats_ggarrange(sce_all_day29_abundances, 
                                       by="cluster_id", 
                                       group_by = "Tx_Group", 
                                       outfile=paste(prefix,"Abundances.Day29.pdf",sep="."),
                                       group_by_palette = Tx_color_palette,
                                       #group_by_stats_ref_group = "Placebo", 
                                       group_by_stats_comparisons = comparisonList,
                                       group_by_stats_method = "wilcox.test",
                                       nrows=2,width_single=80,height_single=120)

plotAbundancesWithStats_ggarrange(sce_all_day0_abundances, 
                                       by="cluster_id", 
                                       group_by = "Tx_Group", 
                                       outfile=paste(prefix,"Abundances.Day0.pdf",sep="."),
                                       group_by_palette = Tx_color_palette,
                                       #group_by_stats_ref_group = "Placebo", 
                                       group_by_stats_comparisons = comparisonList,
                                       group_by_stats_method = "wilcox.test",
                                       nrows=2,width_single=80,height_single=120)

plotAbundancesWithStats_ggarrange(sce_all_day1_29_abundances, 
                                       by="cluster_id", 
                                       group_by = "Tx_Group", 
                                       shape_by = "timepoint",
                                       outfile=paste(prefix,"Abundances.Day1_29.comb.pdf",sep="."),
                                       group_by_palette = Tx_color_palette,
                                       #group_by_stats_ref_group = "Placebo",
                                       group_by_stats_comparisons = comparisonList,
                                       group_by_stats_method = "wilcox.test",
                                       nrows=2,width_single=80,height_single=120)


```

Differential marker expression per population in different timepoints
```{r}
p <- plotPbExprs(sce_all_day1, k = "merging1", facet_by = "cluster_id", shape_by = NULL, color_by="Tx_Group",)
p$facet$params$ncol <- 2

ggsave(p, filename=paste(prefix,"FunctionalMarkerDiffBoxplot.Day1.pdf",sep="."),
           width=240,
           height=320,
           units="mm")

p <- plotPbExprs(sce_all_day29, k = "merging1", facet_by = "cluster_id", shape_by = "patient_id", color_by="Tx_Group",)
p$facet$params$ncol <- 2

ggsave(p, filename=paste(prefix,"FunctionalMarkerDiffBoxplot.Day29.pdf",sep="."),
           width=240,
           height=320,
           units="mm")
```

Compute the diff expressed marker using diffcyt
```{r}
FDR_cutoff <- 0.05
contrast <- createContrast(c(0, 1))
group_by <- "Tx_Group" 

Tx_List <- levels(sce_all[[group_by]])
comparisons <- list(c(1,2),c(1,3))
input_sce <- sce_all_day0

comb_df <- NULL
sce_list <- list()
sce_list[["Day1"]] <- sce_all_day1
sce_list[["Day29"]] <- sce_all_day29

pval_vector <- c()

for(time1 in names(sce_list)){
    input_sce <- sce_list[[time1]]
    
    for(i in comparisons){
        #print(i)
        Curr_Tx_list <- Tx_List[i]
        curr_sce <- filterSCE(input_sce, Tx_Group %in% Curr_Tx_list)    
        
        ei <- metadata(curr_sce)$experiment_info
        ds_formula <- createFormula(ei, cols_fixed = group_by)
    
        ds_res <- diffcyt(curr_sce, 
        formula = ds_formula, contrast = contrast,
        analysis_type = "DS", method_DS = "diffcyt-DS-LMM",
        clustering_to_use = "merging1", verbose = T, seed_clustering = fixed_seed)
    
        df <- as.data.frame(topTable(ds_res, all=T, order_by = "cluster_id", 
                                     format_vals = TRUE, digits = 3)) %>%
                            dplyr::filter(!is.na(p_val) & cluster_id != "others")
        
        df$comparison <- paste(Curr_Tx_list,collapse ="_")
        df$timepoint <- time1
        
        if(is.null(comb_df)){
            comb_df <- df
        }
        else{
            comb_df <- as.data.frame(rbind(comb_df,df))
        }
        
        pval_vector <- c(pval_vector,unlist(df$p_val))
    }
}

comb_df$p_adj <- p.adjust(pval_vector)
#write.csv(comb_df,file=paste(prefix,"MarkerExprDiff.csv",sep="."))

```

```{r}

# x <- sce_all_day1
# k <- "merging1" 
# group_by = "Tx_Group"
# #features = "state"
# features = panel$fcs_colname
# assay = "exprs"
# fun = "median"

GetSummarizedExpr <- function (x, k = "meta20", features = "state", assay = "exprs", 
    fun = c("median", "mean", "sum"), group_by = "condition") 
{
    fun <- match.arg(fun)
    CATALYST:::.check_sce(x, TRUE)
    k <- CATALYST:::.check_k(x, k)
    
    CATALYST:::.check_assay(x, assay)
    CATALYST:::.check_cd_factor(x, group_by)

    ##subset by features (CD markers)
    x <- x[CATALYST:::.get_features(x, features), ]
    x$cluster_id <- cluster_ids(x, k)
    by <- c("cluster_id", "sample_id")
    dim(x)
    table(x$cluster_id)
    table(x$patient_id)
    
    ##aggregate
    ms <- CATALYST:::.agg(x, by, fun, assay)
    df <- melt(ms, varnames = c("antigen", by[length(by)]))
    names(df)[ncol(df)] <- "cluster_id"
    df$cluster_id <- factor(df$cluster_id, levels(x$cluster_id))

    ##add other metadata columns from sce
    i <- match(df$sample_id, x$sample_id)
    j <- setdiff(names(colData(x)), c(names(df)))
    df <- cbind(df, colData(x)[i, j, drop = FALSE])
    ncs <- table(as.list(colData(x)[by]))
    
    ncs <- rep(c(t(ncs)), each = nrow(x))
    
    #add number of cells per cluster in each sample
    df$n_cells <- ncs
    df <- df[ncs > 0, , drop = FALSE]
    
    df
}

##draw multiple marker/antigen per cell cluster/type
plotMarkerExprDiff_ggarrange <- function(df, features=NULL, 
                                             cluster_list=NULL, 
                                             group_by = "condition", 
                                             shape_by = NULL,    
                                             outprefix="median_expr", 
                                             group_by_palette = CATALYST:::.cluster_cols,
                                             group_by_stats_ref_group = NULL, 
                                             group_by_stats_comparisons = NULL, 
                                             group_by_stats_method = "t.test",
                                             nrows=3,width_single=40,height_single=60){

    if(is.null(cluster_list)){
        cluster_list <- levels(df %>% pull(.,var="cluster_id"))
    }

    if(is.null(features)){
        features <- levels(df %>% pull(.,var="antigen"))
    }

    if(is.null(shape_by)){
        columnToSelect <- c(group_by,"value")
    }else{
        columnToSelect <- c(group_by,shape_by,"value")
    }
    
    
    for(i in 1:length(cluster_list)){
        panels <- list()
        
        for(j in 1:length(features)){
            subtable <- df %>% dplyr::filter(cluster_id == cluster_list[i] & antigen == features[j]) %>%
                               dplyr::select(all_of(columnToSelect))

            y1 = ggboxplot(subtable, 
                         x = group_by, 
                         y = "value",
                         color = group_by, 
                         palette = group_by_palette,
                         size=1.5, outlier.shape = NA)
              
            if(is.null(shape_by)){      
                y1 = y1 + geom_point(aes_(fill=as.name(group_by)), 
                         size = 2, shape=21, 
                         position = position_jitterdodge())
            }else{
                y1 = y1 + geom_point(aes_(fill=as.name(group_by),shape=as.name(shape_by)), 
                         size = 2, col="black", position = position_jitterdodge())+
                         scale_shape_manual(values=21:22)
            }
            
            y1 = y1 + theme(
                    panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(), 
                    axis.line = element_line(colour = "black"),
                    axis.text.x = element_blank(),
                    axis.text.y = element_text(size=18),
                    axis.ticks.x = element_blank(),
                    axis.title = element_blank(),
                    legend.position = "none",
                    plot.title=element_text(size=18))+
                  ggtitle(features[j])
            
                if(!is.null(group_by_stats_ref_group)){
                    y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + 
                              stat_compare_means(ref.group = group_by_stats_ref_group, 
                                     size=5, hide.ns = T, method = group_by_stats_method, label = "p.format",vjust=-1)
                }else{
                    if(!is.null(group_by_stats_comparisons)){
                        y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + 
                                  stat_compare_means(comparisons = group_by_stats_comparisons, 
                                         size=5, hide.ns = T, method = group_by_stats_method,label = "p.format")
                    }else{
                        ## default comparison (can be pairwise or group)
                        y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + stat_compare_means(size=5, hide.ns = T, vjust=-3)  
                    }
                }
            
            panels[[j]]=y1
        }
        
        ncols <- floor(length(features)/nrows)
        y <- ggarrange(plotlist=panels,ncol=ncols,nrow=nrows)
    
        ggsave(y, filename=paste(outprefix,cluster_list[i],"SelectMarkerExpr.pdf",sep="."),
           width=width_single*ncols,
           height=height_single*nrows,
           units="mm")
        
    }
}

##draw multiple marker/antigen across timepoints/groups per cell cluster/type
plotMarkerExprDiff_withFacet_ggarrange <- function(df, features=NULL, 
                                             cluster_list=NULL,
                                             group_by = "condition",
                                             facet_by = NULL,
                                             outprefix="median_expr",
                                             group_by_palette = CATALYST:::.cluster_cols,
                                             group_by_stats_ref_group = NULL,
                                             group_by_stats_comparisons = NULL,
                                             group_by_stats_method = "t.test",
                                             nrows=3,width_single=40,height_single=60){

    if(is.null(cluster_list)){
        cluster_list <- levels(df %>% pull(.,var="cluster_id"))
    }

    if(is.null(features)){
        features <- levels(df %>% pull(.,var="antigen"))
    }

    if(is.null(facet_by)){
        columnToSelect <- c(group_by,"value")
    }else{
        columnToSelect <- c(group_by,facet_by,"value")
    }
    
    for(i in 1:length(cluster_list)){
        panels <- list()
        
        for(j in 1:length(features)){
            subtable <- df %>% dplyr::filter(cluster_id == cluster_list[i] & antigen == features[j]) %>%
                               dplyr::select(all_of(columnToSelect))

           
            
            y1 = ggboxplot(subtable, 
                         x = group_by, 
                         y = "value",
                         color = group_by, 
                         palette = group_by_palette,
                         size=1.5, outlier.shape = NA)
            
            if(is.null(shape_by)){      
                y1 = y1 + geom_point(aes_(fill=as.name(group_by)), 
                         size = 2, shape=21, 
                         position = position_jitterdodge())
            }else{
                y1 = y1 + geom_point(aes_(fill=as.name(group_by),shape=as.name(shape_by)), 
                         size = 2, col="black", position = position_jitterdodge())+
                         scale_shape_manual(values=21:22)
            }
            
            y1 = y1 + theme(
                    panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(), 
                    axis.line = element_line(colour = "black"),
                    axis.text.x = element_blank(),
                    axis.text.y = element_text(size=18),
                    axis.ticks.x = element_blank(),
                    axis.title = element_blank(),
                    legend.position = "none",
                    plot.title=element_text(size=18))+
                  ggtitle(features[j])
            
                if(!is.null(group_by_stats_ref_group)){
                    y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + 
                              stat_compare_means(ref.group = group_by_stats_ref_group, 
                                     size=5, hide.ns = T, method = group_by_stats_method, 
                                     label = "p.format",vjust=-1)
                }else{
                    if(!is.null(group_by_stats_comparisons)){
                        y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + 
                                  stat_compare_means(comparisons = group_by_stats_comparisons, 
                                         size=5, hide.ns = T, method = group_by_stats_method,
                                         label = "p.format")
                    }else{
                        ## default comparison (can be pairwise or group)
                        y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + stat_compare_means(size=5, hide.ns = T, vjust=-3)  
                    }
                }
            
            y1 <- y1+facet_wrap(facet_by)
            
            panels[[j]]=y1
        }
        
        ncols <- floor(length(features)/nrows)
        y <- ggarrange(plotlist=panels,ncol=ncols,nrow=nrows)
    
        ggsave(y, filename=paste(outprefix,cluster_list[i],"SelectMarkerExpr.pdf",sep="."),
           width=width_single*ncols,
           height=height_single*nrows,
           units="mm")
    }
}

##draw multiple marker/antigen across timepoints/groups per cell cluster/type
plotMarkerExprDiff_withFacetByMarker_ggarrange <- function(df, features=NULL, 
                                             cluster_list=NULL,
                                             group_by = "condition",
                                             facet_by = NULL,
                                             outprefix="median_expr",
                                             group_by_palette = CATALYST:::.cluster_cols,
                                             group_by_stats_ref_group = NULL,
                                             group_by_stats_comparisons = NULL,
                                             group_by_stats_method = "t.test",
                                             nrows=3,width_single=40,height_single=60){

    if(is.null(cluster_list)){
        cluster_list <- levels(df %>% pull(.,var="cluster_id"))
    }

    if(is.null(features)){
        features <- levels(df %>% pull(.,var="antigen"))
    }

    if(is.null(facet_by)){
        columnToSelect <- c(group_by,"value")
    }else{
        columnToSelect <- c(group_by,facet_by,"value")
    }
    
    for(i in 1:length(features)){
        panels <- list()
        
        for(j in 1:length(cluster_list)){
            subtable <- df %>% dplyr::filter(cluster_id == cluster_list[j] & antigen == features[i]) %>%
                               dplyr::select(all_of(columnToSelect))
            
            y1 = ggboxplot(subtable, 
                         x = group_by, 
                         y = "value",
                         color = group_by, 
                         palette = group_by_palette,
                         size=1.5, outlier.shape = NA)
            
            if(is.null(shape_by)){      
                y1 = y1 + geom_point(aes_(fill=as.name(group_by)), 
                         size = 2, shape=21, 
                         position = position_jitterdodge())
            }else{
                y1 = y1 + geom_point(aes_(fill=as.name(group_by),shape=as.name(shape_by)), 
                         size = 2, col="black", position = position_jitterdodge())+
                         scale_shape_manual(values=21:22)
            }
            
            y1 = y1 + theme(
                    panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(), 
                    axis.line = element_line(colour = "black"),
                    axis.text.x = element_blank(),
                    axis.text.y = element_text(size=18),
                    axis.ticks.x = element_blank(),
                    axis.title = element_blank(),
                    legend.position = "none",
                    plot.title=element_text(size=18))+
                  ggtitle(cluster_list[j])
            
                if(!is.null(group_by_stats_ref_group)){
                    y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + 
                              stat_compare_means(ref.group = group_by_stats_ref_group, 
                                     size=5, hide.ns = T, method = group_by_stats_method, 
                                     label = "p.format",vjust=-1)
                }else{
                    if(!is.null(group_by_stats_comparisons)){
                        y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + 
                                  stat_compare_means(comparisons = group_by_stats_comparisons, 
                                         size=5, hide.ns = T, method = group_by_stats_method,
                                         label = "p.format")
                    }else{
                        ## default comparison (can be pairwise or group)
                        y1<- y1 + scale_y_continuous(expand=expansion(mult=c(0.1,0.1))) + stat_compare_means(size=5, hide.ns = T, vjust=-3)  
                    }
                }
            
            y1 <- y1+facet_wrap(facet_by)
            
            panels[[j]]=y1
        }
        
        ncols <- floor(length(cluster_list)/nrows)
        y <- ggarrange(plotlist=panels,ncol=ncols,nrow=nrows)
    
        ggsave(y, filename=paste(outprefix,features[i],"GroupByMarker.pdf",sep="."),
           width=width_single*ncols,
           height=height_single*nrows,
           units="mm")
    }
}


```
 
```{r}

Tx_color_palette <- c("#5C899B","#9B5C89","#899B5C")
comparisonList <- list(c("Placebo","PolyICLC"),c("Placebo","Resiquimod"))


summaryMedianExprPerMarker_Day0 <- GetSummarizedExpr(sce_all_day0, k = "merging1", group_by = "Tx_Group")
summaryMedianExprPerMarker_Day1 <- GetSummarizedExpr(sce_all_day1, k = "merging1", group_by = "Tx_Group")
summaryMedianExprPerMarker_Day29 <- GetSummarizedExpr(sce_all_day29, k = "merging1", group_by = "Tx_Group")
summaryMedianExprPerMarker_Day1_29 <- GetSummarizedExpr(sce_all_day1_29, k = "merging1", group_by = "Tx_Group")

summaryMedianExprPerMarker <- as.data.frame(rbind(summaryMedianExprPerMarker_Day0,
                                                   summaryMedianExprPerMarker_Day1,
                                                   summaryMedianExprPerMarker_Day29))
write.csv(summaryMedianExprPerMarker,file=paste(prefix,"MedianMarkerExpr.withD0.csv",sep="."))

antigen_list <- c("CD39","TIGIT","CD38","CD27",
           "Ki67","CD45RA","PD1","PDL1",
           "CD127","CD45RO","CD69","CD25")

cluster_subset <- c("CD8 T","CD4 T","NK","CD14 monocyte",
                    "CD16 monocyte","B","Treg") 

##only draw those with nominal p-value <= 0.05 in the diff exp analysis
plotMarkerExprDiff_ggarrange(summaryMedianExprPerMarker_Day1, features=antigen_list, 
                                 cluster_list=cluster_subset, 
                                 group_by = "Tx_Group", 
                                 outprefix=paste(prefix,"Day1",sep="."), 
                                 group_by_palette = Tx_color_palette,
                                 #group_by_stats_ref_group = "Placebo", 
                                 group_by_stats_comparisons = comparisonList,
                                 group_by_stats_method = "wilcox.test",
                                 nrows=3,width_single=80,height_single=100)

plotMarkerExprDiff_ggarrange(summaryMedianExprPerMarker_Day29, features=antigen_list, 
                                 cluster_list=cluster_subset, 
                                 group_by = "Tx_Group", 
                                 outprefix=paste(prefix,"Day29",sep="."), 
                                 group_by_palette = Tx_color_palette,
                                 #group_by_stats_ref_group = "Placebo", 
                                 group_by_stats_comparisons = comparisonList,
                                 group_by_stats_method = "wilcox.test",
                                 nrows=3,width_single=80,height_single=100)

plotMarkerExprDiff_ggarrange(summaryMedianExprPerMarker_Day1_29, features=antigen_list,
                                 cluster_list=cluster_subset,
                                 group_by = "Tx_Group", 
                                 shape_by = "timepoint",
                                 outprefix=paste(prefix,"Day1_29",sep="."), 
                                 group_by_palette = Tx_color_palette,
                                 #group_by_stats_ref_group = "Placebo", 
                                 group_by_stats_comparisons = comparisonList,
                                 group_by_stats_method = "wilcox.test",
                                 nrows=3,width_single=80,height_single=100)

```

```{r}
##draw additional figures across all timepoints

antigen_list <- c("CD39","TIGIT","CD38","CD27",
           "Ki67","CD45RA","PD1","PDL1",
           "CD127","CD45RO","CD69","CD25",
           "CD152","TIM3","HLA_DR")

cluster_subset <- c("CD8 T","CD4 T","NK","CD14 monocyte",
                    "CD16 monocyte","B","Treg","CD8 T") 


antigen_list <- c("CD27","CD69","CD25",
           "Ki67","CD127","PD1")

cluster_subset <- c("CD8 T") 


plotMarkerExprDiff_withFacet_ggarrange(summaryMedianExprPerMarker, 
                                    features=antigen_list, 
                                    cluster_list=cluster_subset, 
                                    group_by = "Tx_Group", 
                                    facet_by = "timepoint",
                                    outprefix=paste(prefix,"allTimepoint",sep="."), 
                                    group_by_palette = Tx_color_palette,
                                 group_by_stats_comparisons = comparisonList,
                                 group_by_stats_method = "wilcox.test",
                                 nrows=5,width_single=80,height_single=100)

plotMarkerExprDiff_withFacetByMarker_ggarrange(summaryMedianExprPerMarker, 
                                    features=antigen_list, 
                                    cluster_list=cluster_subset,
                                    group_by = "Tx_Group", 
                                    facet_by = "timepoint",
                                    outprefix=paste(prefix,"allTimepoint",sep="."), 
                                    group_by_palette = Tx_color_palette,
                                 group_by_stats_comparisons = comparisonList,
                                 group_by_stats_method = "wilcox.test",
                                 nrows=2,width_single=80,height_single=100)

# df <- summaryMedianExprPerMarker 
# features=antigen_list
# cluster_list=cluster_subset
# facet_by ="timepoint"
# outprefix=paste(prefix,"ByTimepoint","Tx",sep=".")
# group_by_palette = Tx_color_palette
# group_by_stats_ref_group = NULL
# group_by_stats_comparisons = comparisonList
# group_by_stats_method = "wilcox.test"
# nrows=3
# width_single=80
# height_single=100




```

